In [1]:
import pandas as pd
import numpy as np
beta=1 #STIFFNESS
# Loading and trasforming into a numpy matrix the dataset
df=pd.read_csv('Iris.csv')
selected_columns = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
data_matrix = df[selected_columns].to_numpy()
print("Data matrix:")
print(data_matrix)
print(f"shape: {data_matrix.shape}")

Data matrix:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]

In [2]:
#Finding the range of the dataset
max_values=df[selected_columns].max()
min_values=df[selected_columns].min()

# Generate initial centroids randomly within the range of the dataset
initial_centroids=np.random.uniform(min_values, max_values, (3,4))
print("Initial centroids:")
print(initial_centroids)

Initial centroids:
[[6.4377174  4.17278671 3.99181337 1.24766903]
 [6.8360886  4.03017446 5.72086836 0.96281965]
 [6.28201374 3.35410348 5.9770345  2.26245988]]


In [3]:
# Euclidean distance function
def d(a,b):
    return np.sqrt(np.sum((a-b)**2))

In [4]:
# First assignment
responsibilities=np.zeros((data_matrix.shape[0],3))
for i in range(data_matrix.shape[0]):
    distances = np.array([d(data_matrix[i], centroid) for centroid in initial_centroids])
    responsibilities[i]=np.exp(-beta*distances)/np.sum(np.exp(-beta*distances))
#print("Initial responsibilities:")
#print(responsibilities)


In [5]:
for k in range(10):
    # Calculating the new centroids
    for j in range(3):
        r_j = responsibilities[:, j] # prendo le colonne della matrice responsibilities
        initial_centroids[j] = np.sum(r_j[:, np.newaxis] * data_matrix, axis=0) / np.sum(r_j)

    # Updating the responsibilities with the new centroids
    for i in range(data_matrix.shape[0]):
        distances = np.array([d(data_matrix[i], centroid) for centroid in initial_centroids])
        responsibilities[i]=np.exp(-beta*distances)/np.sum(np.exp(-beta*distances))

print(np.sum(responsibilities[:, 0]))
print(np.sum(responsibilities[:, 1]))
print(np.sum(responsibilities[:, 2]))
print(responsibilities)

52.22519654127488
48.83505232257516
48.939751136149965
[[0.94464506 0.0298545  0.02550043]
 [0.93925611 0.03285068 0.02789321]
 [0.94387746 0.03034559 0.02577695]
 [0.93701394 0.03408163 0.02890442]
 [0.94420038 0.03009076 0.02570886]
 [0.90608069 0.05044035 0.04347897]
 [0.94185833 0.03141931 0.02672235]
 [0.94656652 0.02884657 0.02458691]
 [0.92962382 0.03810833 0.03226785]
 [0.94093843 0.03193492 0.02712665]
 [0.92770866 0.03888662 0.03340472]
 [0.94331698 0.03062271 0.02606031]
 [0.93905683 0.03296858 0.02797459]
 [0.93725194 0.03396757 0.02878049]
 [0.90517633 0.05076917 0.0440545 ]
 [0.87479886 0.06683535 0.0583658 ]
 [0.92302308 0.04134108 0.03563585]
 [0.94419461 0.03009521 0.02571018]
 [0.89001716 0.05899499 0.05098785]
 [0.9343132  0.03536345 0.03032335]
 [0.92586249 0.03995376 0.03418374]
 [0.93623887 0.03434465 0.02941648]
 [0.94497267 0.02970421 0.02532312]
 [0.93727214 0.03386664 0.02886123]
 [0.92812328 0.03883506 0.03304166]
 [0.93479496 0.03526054 0.02994451]
 [0.94500